language: ruby

rvm:
  - 2.1.0
  - 2.1.7
  - 2.2.3
  - ruby-head
  - rbx-2

branches:
  only:
    - master

sudo: false

script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
